[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Optional: simple redirects if you ever add /insights etc as real routes
# [[redirects]]
#   from = "/insights"
#   to = "/index.html"
#   status = 200

[[redirects]]
  from = "/project/thomson-reserve-condo"
  to = "/project/thomson-reserve-condo/index.html"
  status = 200
